name: Subgraph Build Workflow
on:
    workflow_call:
        inputs:
            PACKAGE_NAME:
                required: true
                type: string
            PACKAGE_DIR:
                required: true
                type: string
            NETWORK:
                required: false
                type: "string"
                default: "goerli"
        secrets:
            PROJECT_ID:
                required: true
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "yarn"
            - run: yarn install --frozen-lockfile
            - name: Code format check
              run: yarn prettier
            - run: yarn workspace ${{ inputs.PACKAGE_NAME }} prepare:${{inputs.NETWORK}}
              env:
                  PROJECT_ID: ${{ secrets.PROJECT_ID }}
            - run: mv ./${{ inputs.PACKAGE_DIR }}/subgraph.${{inputs.NETWORK}}.yaml ./${{ inputs.PACKAGE_DIR }}/subgraph.yaml
            - run: yarn workspace ${{ inputs.PACKAGE_NAME }} codegen
            - run: yarn workspace ${{ inputs.PACKAGE_NAME }} build
            - run: yarn workspace ${{ inputs.PACKAGE_NAME }} test
