name: Subgraph Build Workflow
on:
    workflow_call:
        inputs:
            PACKAGE_NAME:
                required: true
                type: string
            PACKAGE_DIR:
                required: true
                type: string
        secrets:
            PROJECT_ID:
                required: true
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - run: yarn install
            - name: Code format check
              run: yarn prettier
            - run: yarn workspace ${{ inputs.PACKAGE_NAME }} prepare:goerli
              env:
                  PROJECT_ID: ${{ secrets.PROJECT_ID }}
            - run: mv ./${{ inputs.PACKAGE_DIR }}/subgraph.goerli.yaml ./${{ inputs.PACKAGE_DIR }}/subgraph.yaml
            - run: yarn workspace ${{ inputs.PACKAGE_NAME }} codegen
            - run: yarn workspace ${{ inputs.PACKAGE_NAME }} build
            - run: yarn workspace ${{ inputs.PACKAGE_NAME }} test
