name: Publish
on:
  pull_request:
    paths:
      - "packages/eligibility/**"
      - ".github/workflows/eligibility.yml"
  push:
    paths:
      - "packages/eligibility/**"
      - ".github/workflows/eligibility.yml"
    tags:
      - v**
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: yarn

      # @dev tests need updates and fixes
      # - name: Test
      #   run: yarn test

      - name: Code format check
        run: yarn prettier

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: cartesi/eligibility
          tag-semver: |
            {{version}}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: ./packages/eligibility/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.CI_TOKEN }}
