name: PoS Subgraph
on:
    push:
        paths:
            - "packages/pos-subgraph/**"
            - "packages/toolbox/**"
            - ".github/workflows/pos-subgraph.yml"
            - ".github/workflows/called-subgraph-build.yml"
jobs:
    build:
        uses: ./.github/workflows/called-subgraph-build.yml
        with:
            PACKAGE_NAME: cartesi-subgraph
            PACKAGE_DIR: ./packages/pos-subgraph
        secrets:
            PROJECT_ID: ${{ secrets.PROJECT_ID }}
